"""empty message

Revision ID: 957a22a9c8f4
Revises: a85d324ab576
Create Date: 2021-02-25 08:20:39.667895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957a22a9c8f4'
down_revision = 'a85d324ab576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'user_id')
    # ### end Alembic commands ###
